# Generated by Django 4.1.2 on 2022-10-29 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='courses',
            new_name='Course',
        ),
    ]
